server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: OrderService
    password: ${DB_PASSWORD_ORDERS}  # viene de Vault
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.OracleDialect
